### ISSUE TITLE
Pipeline fails when running on input_myco_tiny.csv dataset.

### ISSUE THREAD

**Issue by FernandoDuarteF** [nf-core/genomeqc#55]
Pipeline fails on BUSCO step when running on testdata.

The problem seems to be related to the ``input_myco_tiny.csv`` dataset.

Choosing ``bacteria_odb10`` as lineage to run BUSCO fixes the issue, but we should probably have a look at other alternatives.

**Comment by FernandoDuarteF** [comment]
Log error:

```
Command error:
  2024-10-25 14:10:36 INFO:     [hmmsearch]     4 of 34 task(s) completed
  2024-10-25 14:10:36 INFO:     [hmmsearch]     7 of 34 task(s) completed
  2024-10-25 14:10:36 INFO:     [hmmsearch]     11 of 34 task(s) completed
  2024-10-25 14:10:36 INFO:     [hmmsearch]     14 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     17 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     21 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     24 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     28 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     31 of 34 task(s) completed
  2024-10-25 14:10:37 INFO:     [hmmsearch]     34 of 34 task(s) completed
  2024-10-25 14:10:37 WARNING:  BUSCO did not find any match. Make sure to check the log files if this is unexpected.
  2024-10-25 14:10:37 CRITICAL: Unhandled exception occurred:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/busco/BuscoRunner.py", line 120, in run
...skipping...
    File "/usr/local/lib/python3.7/site-packages/busco/analysis/BuscoAnalysis.py", line 141, in run_hmmer
      self.record_results()
    File "/usr/local/lib/python3.7/site-packages/busco/analysis/GenomeAnalysis.py", line 1081, in record_results
      self.hmmer_runner.record_results()
    File "/usr/local/lib/python3.7/site-packages/busco/busco_tools/hmmer.py", line 1210, in record_results
      self._get_busco_percentages()
    File "/usr/local/lib/python3.7/site-packages/busco/busco_tools/hmmer.py", line 1309, in _get_busco_percentages
      self._get_stop_codon_percent_and_avg_identity()
    File "/usr/local/lib/python3.7/site-packages/busco/busco_tools/hmmer.py", line 1359, in _get_stop_codon_percent_and_avg_identity
      self.avg_identity = round(sum(identities) / len(identities), 2)
  ZeroDivisionError: division by zero


  2024-10-25 14:10:37 ERROR:	division by zero
  2024-10-25 14:10:37 ERROR:	BUSCO analysis failed!
  2024-10-25 14:10:37 ERROR:	Check the logs, read the user guide (https://busco.ezlab.org/busco_userguide.html), and check the BUSCO issue board on https://gitlab.com/ezlab/busco/issues
```

**Comment by FernandoDuarteF** [comment]
Might be related #85.

**Comment by chriswyatt1** [comment]
It works now
